name: Flutter iOS Build

on:
  push:
    branches:
      - main  # or your preferred branch
  pull_request:
    branches:
      - main  # or your preferred branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS to build iOS apps

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # You can specify a specific version if needed

    - name: Run flutter pub get
      run: flutter pub get

    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign

    - name: Archive iOS Build
      run: |
        cd build/ios/iphoneos
        zip -r iOSApp.zip Runner.app
