name: Build Flutter iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter iOS App
    runs-on: macos-latest  # Ensure the job runs on macOS

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Specify the Flutter version

      # Step 3: Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-cache-${{ hashFiles('**/pubspec.yaml') }}

      # Step 4: Install CocoaPods (if not already installed)
      - name: Install CocoaPods
        run: gem install cocoapods

      # Step 5: Cache CocoaPods dependencies to speed up builds
      - name: Cache CocoaPods dependencies
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}

      # Step 6: Update CocoaPods repositories (necessary if pods need to be updated)
      - name: Update CocoaPods Repositories
        run: pod repo update

      # Step 7: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 8: Install iOS dependencies (CocoaPods) and resolve any issues
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      # Step 9: Clean Flutter build (optional but recommended for CI)
      - name: Clean Flutter build
        run: flutter clean

      # Step 10: Build the iOS app for release (no code signing required for CI)
      - name: Build Flutter iOS app
        run: flutter build ios --release --no-codesign

      # Step 11: Upload build artifacts (iOS .app file)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
