name: Build Flutter iOS APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter iOS APK
    runs-on: macos-latest  # This ensures the job runs on macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # You can specify a specific Flutter version here

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Update CocoaPods Repositories
        run: |
          pod repo update

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Install iOS Dependencies
        run: |
          cd ios
          pod install

      - name: Build Flutter iOS APK
        run: |
          flutter build ios --release --no-codesign

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
