name: Build Flutter iOS APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter iOS APK
    runs-on: macos-latest  # This ensures the job runs on macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # You can specify a specific Flutter version here

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build Flutter iOS APK
        run: |
          flutter build ios --release --no-codesign
          # The `--no-codesign` flag prevents the need for signing the app. Remove if you plan to sign it.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Updated version
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
