name: Flutter iOS Build

on:
  push:
    branches:
      - main  # or your preferred branch
  pull_request:
    branches:
      - main  # or your preferred branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS to build iOS apps

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # Specify a stable version here

    - name: Run flutter doctor
      run: flutter doctor

    - name: Clear Pub Cache
      run: flutter pub cache repair

    - name: Run flutter pub get
      run: flutter pub get --verbose  # Get more details if it fails

    - name: Switch to stable channel
      run: flutter channel stable

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Archive iOS Build
      run: |
        cd build/ios/iphoneos
        zip -r iOSApp.zip Runner.app
