name: Flutter iOS Build

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Specify the Flutter version you want to use

      - name: Install Dependencies
        run: |
          flutter pub get
          
      - name: Build iOS
        run: |
          flutter build ios --release
          
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos/*.app # Adjust path based on your project structure

      - name: Clean Up
        run: |
          flutter clean
